### ISSUE TITLE
Blocklist talk

### ISSUE THREAD

**Issue by Tascani** [Raulfin/PCaPP#212]
What is the general stance on blocklist entries?
Do we add entries for consistency reasons only? (all DA mods are on the list)

Example:
da_alternate_start_extension.esp (an extension to Death Alternative [DA])

It is not necessary to blocklist it as it has no record groups that PaMa would process.

What happens if the patcher is told to ignore (Blocklist) an .esp ... does it speed up the patching proces when the blocked .esp contains no records to process anyway?

Example 2:
We have a random mod which adds a new worldspace, a lot of stuff, quests, statics anything that PaMa would ignore. (say 10000 records)
Does PaMa scan it fully? How much time does this need while patching just to see that it doesn't need patching?
Is PaMa only checking the record groups or does it check each record?

**Comment by Raulfin** [comment]
PaMa only imports major records from;
WEAP, ARMO, COBJ, RACE, MGEF, BOOK, SPEL, ALCH, ENCH, NPC_, INGR, ALCH, AMMO, PROJ, NPC_, GMST, GLOB, SCRL, FLST, LVLI
what gets blocked depends on a few things; does patching it actually change anything, is it breaking anything.
Like I added Convenient Horses to the block after getting everything set up for it and finding that the patcher doesn't make any changes, but creates a lot of ITMs in PatchusMaxamus.esp, this made it pretty pointless to patch, blocking stuff like that will make the patcher run a little faster since it doesn't have to parse 1500 items to do nothing to.

PSQ PlayerSuccubusQuest.esm or Animated Dragon Wings.esp (whichever is SexLab) got blocked after a few days of testing by a friend found that patching was making no changes, but was breaking a main function of the mod (flight).

Stuff like HorseCloakCH.esp and HorseCloak.esp I blocked as they just add armors for Horses and don't need to be patched (patching would either do nothing or "break" them).

Break is a pretty loose term, since PaMa can't tell the difference between stuff like a horse armor and a normal armor it can confuse them and potentially distribute horse armor with normal armor, which would "break" it.
